---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-subchart-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: subchart-example/
    repoURL: https://github.com/pankaj-pal/argocd-helm-subhcart.git
    targetRevision: main
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: subchart-example/
        repoURL: https://github.com/pankaj-pal/argocd-helm-subhcart.git
        targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
